### PR TITLE
Build on ruby 3.1.2

### PR DESCRIPTION
**Pull request by xjunior**

### CODE REVIEW

**Comment by benlangfeld** [comment]
What about https://github.com/powerhome/power_linting/blob/main/rubocop-powerhome/config/default.yml#L2 ?

**Comment by xjunior** [comment]
@benlangfeld that is the oldest version supported:

> Users may let RuboCop know the oldest version of Ruby which your project supports with:
> ```yaml
> AllCops:
>   TargetRubyVersion: 2.5
> ```

**Comment by benlangfeld** [comment]
> @benlangfeld that is the oldest version supported:
> 
> > Users may let RuboCop know the oldest version of Ruby which your project supports with:
> > ```yaml
> > AllCops:
> >   TargetRubyVersion: 2.5
> > ```

Should we recommend that consuming projects override this in our docs?

**Comment by xjunior** [comment]
> > @benlangfeld that is the oldest version supported:
> > > Users may let RuboCop know the oldest version of Ruby which your project supports with:
> > > ```yaml
> > > AllCops:
> > >   TargetRubyVersion: 2.5
> > > ```
> 
> Should we recommend that consuming projects override this in our docs?

Makes sense to me. And actually, remove this from this project?

**Comment by benlangfeld** [comment]
> > > @benlangfeld that is the oldest version supported:
> > > > Users may let RuboCop know the oldest version of Ruby which your project supports with:
> > > > ```yaml
> > > > AllCops:
> > > >   TargetRubyVersion: 2.5
> > > > ```
> > 
> > 
> > Should we recommend that consuming projects override this in our docs?
> 
> Makes sense to me. And actually, remove this from this project?

I don't mind specifying a minimum version here. We might want to also specify it in the gemspec.

**Comment by benlangfeld** [comment]
I think this lib will have a minimum Ruby version it will work on whether we specify it explicitly or not. I don't really mind either way, but I do think we should recommend that users specify something in their apps regardless.

**Review by benlangfeld — APPROVED** [review]

**Review by kaysiz — APPROVED** [review]

**Review by garettarrowood — APPROVED** [review]

**Pull request merged**
